In [1]:
#Que 1

def calc(a, b, op):
    if op == 1:
        return a + b
    elif op == 2:
        return a - b
    elif op == 3:
        return a * b
    elif op == 4:
        if b != 0:
            return a / b
        else:
            print("Division by zero not allowed")
            return None
    else:
        print("Invalid op")
        return None


In [2]:
print(calc(10, 5, 1))  # Addition
print(calc(10, 5, 2))  # Subtraction
print(calc(10, 5, 3))  # Multiplication
print(calc(10, 5, 4))  # Division
print(calc(10, 5, 6))  # Invalid operation


15
5
50
2.0
Invalid op
None


In [3]:
#que 2

def shortest_longest(words):
    shortest = words[0]
    longest = words[0]

    for word in words:
        if len(word) < len(shortest):
            shortest = word
        if len(word) > len(longest):
            longest = word

    return (shortest, longest)


In [4]:
words = ["machine", "ai", "learning", "data"]
result = shortest_longest(words)
print(result)


('ai', 'learning')


In [5]:
#que 3

def add_if_not_present(lst, element):
    if element not in lst:
        lst.append(element)
    return lst


In [6]:
my_list = [1, 2, 3]
print(add_if_not_present(my_list, 4))
print(add_if_not_present(my_list, 2))


[1, 2, 3, 4]
[1, 2, 3, 4]


In [7]:
#que 4

import numpy as np

def get_transpose(arr):
    return arr.T


In [8]:
array = np.array([[1, 2], [3, 4]])
print(get_transpose(array))


[[1 3]
 [2 4]]


In [9]:
#que 5

import numpy as np

def row_vector(lst):
    return np.array(lst).reshape(1, len(lst))


In [10]:
numbers = [10, 20, 30, 40]
print(row_vector(numbers))


[[10 20 30 40]]


In [12]:
#que 6

import numpy as np

def final_column_vector(arr):
    return arr[:, -1].reshape(-1, 1)


In [13]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(final_column_vector(array_2d))


[[3]
 [6]
 [9]]


In [17]:
#que 7

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("adult_data.csv")

# --------- EDA (10 functions) ---------
print(df.head())
print(df.tail())
print(df.shape)
print(df.info())
print(df.describe())
print(df.columns)
print(df.dtypes)
print(df.isnull().sum())
print(df.nunique())
print(df['target'].value_counts())


# --------- Preprocessing ---------
df.replace('?', np.nan, inplace=True)
df.dropna(inplace=True)

for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

print("Preprocessing completed")


   age         workclass  fnlwgt  education  education.num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital.status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital.gain  capital.loss  hours.per.week native.country target  
0          2174             0              40  United-States  <=50K  
1             0             0             

In [16]:
df.head()

age         workclass  fnlwgt  education  education.num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital.status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital.gain  capital.loss  hours.per.week native.country target  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K